#!/usr/bin/env bash
# Creates a PID file, displays messages and handles signals
echo $$ > /tmp/myscript.pid

cleanup() {
    echo "I hate the kill command"
    rm -f /tmp/myscript.pid
    exit 0
}

trap cleanup SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap cleanup SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done